### ISSUE TITLE
我最近做了一个新的脚本 不知道大大感不感兴趣  感兴趣的话可以收录我的新脚本嘛

### ISSUE THREAD

**Issue by sixiansheng** [ChinaGodMan/UserScripts#4]
### 用户故事

https://greasyfork.org/zh-CN/scripts/505571-%E5%8E%9F%E7%94%9F%E5%9B%BE%E7%89%87%E6%B5%8F%E8%A7%88%E5%99%A8
![屏幕截图 2024-08-28 173900](https://github.com/user-attachments/assets/109aec77-9860-4d87-90f2-9bc378951155)
![屏幕截图 2024-08-28 173953](https://github.com/user-attachments/assets/be80a9f3-63cb-42cc-aa4a-fc5d0a04b37f)
![屏幕截图 2024-08-28 174001](https://github.com/user-attachments/assets/186b8ad3-6674-4da3-975e-e244ac9dca9b)
![屏幕截图 2024-08-28 174014](https://github.com/user-attachments/assets/ffe308a9-4a3c-4bbe-aceb-a3a60a764335)

https://github.com/user-attachments/assets/89f2c053-9125-47b1-89f5-4c878ab85c7f

基于浏览器原生看图的脚本

**Comment by ChinaGodMan** [comment]
你已经上传了啊，好脚本啊

**Comment by sixiansheng** [comment]
> 你已经上传了啊，好脚本啊

我只完成了一部分，还有一些没完善，所以就想发上来让大佬看一下。比如小窗的图片上面有一行空行不知道怎么才能去掉，整个页面也是跟顶部对齐了，不知道为什么还会有一行空行
![image](https://github.com/user-attachments/assets/1a7976fe-266c-472e-8a46-378a2353fe5f)

**Comment by ChinaGodMan** [comment]
> > 你已经上传了啊，好脚本啊
> 
> 我只完成了一部分，还有一些没完善，所以就想发上来让大佬看一下。比如小窗的图片上面有一行空行不知道怎么才能去掉，整个页面也是跟顶部对齐了，不知道为什么还会有一行空行 ![image](https://private-user-images.githubusercontent.com/35787924/362243378-1a7976fe-266c-472e-8a46-378a2353fe5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4NDI2MjQsIm5iZiI6MTcyNDg0MjMyNCwicGF0aCI6Ii8zNTc4NzkyNC8zNjIyNDMzNzgtMWE3OTc2ZmUtMjY2Yy00NzJlLThhNDYtMzc4YTIzNTNmZTVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDEwNTIwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1NWFjZDVkYmFmYWJlOWY3ZWEwYzA4ZDkxOWY3ZWY2ZGUwMDViM2YzYWQxZmZiMDJhZjMzZGUzMTViNmJlNzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9hEXDcksV8RyFyXNOm3R4u7f2DQzWIoVovpx89TAdlI)

找个看图的库用也行啊，不弹小窗也行啊
