### ISSUE TITLE
[BUG]预览窗口内为ncbi相关网站时背景模糊以及点按关闭等操作失效

### ISSUE THREAD

**Issue by Guany725** [ChinaGodMan/UserScripts#50]
### 复现步骤

1、随意找一篇pubmed文献如 https://pmc.ncbi.nlm.nih.gov/articles/PMC9357357/ ，找到下方reference，长按’google scholar‘进行预览操作
![image](https://github.com/user-attachments/assets/b3ff07cf-c353-4ca9-8bd6-ddcdc4bd29fb)

### 预期行为

正常情况下打开小窗且背景模糊，失焦自动关闭

### 实际行为

小窗打开后背景未模糊且失去焦点后不正常关闭
![image](https://github.com/user-attachments/assets/edadc85d-d305-4c04-af60-25283f9504fc)

### 环境

chrome，edge均尝试

### 其他信息

在pubmed域名下小窗打开其他链接或在其他网页小窗打开pubmed域名都会出现这种情况

**Comment by ChinaGodMan** [comment]
@Guany725 你不妨说的明白些

**Comment by Guany725** [comment]
> @Guany725 你不妨说的明白些

不好意思当时没写清楚

**Comment by ChinaGodMan** [comment]
> > @Guany725 你不妨说的明白些
> 
> 不好意思当时没写清楚

跨域限制。无法访问弹出窗口的状态。在`https://pmc.ncbi.nlm.nih.gov/`点击之后打开的是  `https://scholar.google.com/`域名。解决太麻烦了
